-- Episode danmaku used to be persisted even when the episode key only matched
-- through a fallback, so a wrong URL could become the permanent guid -> URL
-- mapping and every episode of a season then served the same danmaku. The
-- write path now stores only exact matches and skips duplicates, so the rows
-- left by the old behaviour are stale and must be dropped to be re-resolved.
--
-- The table is also renamed: it never held general playback links, only the
-- platform page used to fetch an episode's danmaku.
CREATE TABLE IF NOT EXISTS DANMU_PLATFORM_URL (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid VARCHAR(255),
    parent_guid VARCHAR(255),
    url VARCHAR(2048)
    );
COMMENT ON TABLE DANMU_PLATFORM_URL IS '剧集弹幕源链接缓存表(记录某集在视频平台的播放页地址,供弹幕抓取使用)';
COMMENT ON COLUMN DANMU_PLATFORM_URL.id IS '主键ID';
COMMENT ON COLUMN DANMU_PLATFORM_URL.guid IS '剧集ID';
COMMENT ON COLUMN DANMU_PLATFORM_URL.parent_guid IS '母ID(例如季度ID)';
COMMENT ON COLUMN DANMU_PLATFORM_URL.url IS '弹幕源页面链接';

DROP TABLE IF EXISTS VIDEO_CONFIG_URL;