-- Commercials can occur several times per episode, so they move from the single
-- commercial_start/commercial_end pair on EPISODE_SEGMENTS into their own child table.
CREATE TABLE IF NOT EXISTS COMMERCIAL_SEGMENTS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_segment_id BIGINT NOT NULL,
    ordinal INT NOT NULL,
    start_time DECIMAL(10, 3) NOT NULL,
    end_time DECIMAL(10, 3) NOT NULL,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);
COMMENT ON TABLE COMMERCIAL_SEGMENTS IS '剧集广告片段表(一部剧集可有多段)';
COMMENT ON COLUMN COMMERCIAL_SEGMENTS.episode_segment_id IS '所属剧集片段记录ID';
COMMENT ON COLUMN COMMERCIAL_SEGMENTS.ordinal IS '片段顺序(从0开始)';
COMMENT ON COLUMN COMMERCIAL_SEGMENTS.start_time IS '广告开始时间(秒)';
COMMENT ON COLUMN COMMERCIAL_SEGMENTS.end_time IS '广告结束时间(秒)';

CREATE INDEX IF NOT EXISTS idx_commercial_segments_episode_segment_id
    ON COMMERCIAL_SEGMENTS (episode_segment_id);

ALTER TABLE EPISODE_SEGMENTS DROP COLUMN IF EXISTS commercial_start;
ALTER TABLE EPISODE_SEGMENTS DROP COLUMN IF EXISTS commercial_end;
