CREATE TABLE IF NOT EXISTS DANMU_SOURCE_CONFIG (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR(32) NOT NULL,
    name VARCHAR(128),
    url VARCHAR(512) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE,
    create_time TIMESTAMP,
    update_time TIMESTAMP
    );
COMMENT ON TABLE DANMU_SOURCE_CONFIG IS '弹幕源配置表(弹弹play中转与第三方兜底弹幕服务器,可在客户端设置页运行时修改)';
COMMENT ON COLUMN DANMU_SOURCE_CONFIG.id IS '主键ID';
COMMENT ON COLUMN DANMU_SOURCE_CONFIG.source_type IS '配置类型: dandan_relay=弹弹play中转(单行), fallback_server=第三方兜底弹幕服务器(可多行)';
COMMENT ON COLUMN DANMU_SOURCE_CONFIG.name IS '显示名称(兜底服务器用,弹弹行为空)';
COMMENT ON COLUMN DANMU_SOURCE_CONFIG.url IS '服务器基地址(弹弹为ddp中转地址,兜底为 ?url=&ac=dm 契约服务器)';
COMMENT ON COLUMN DANMU_SOURCE_CONFIG.enabled IS '是否启用(FALSE=停用但保留配置)';
COMMENT ON COLUMN DANMU_SOURCE_CONFIG.create_time IS '创建时间';
COMMENT ON COLUMN DANMU_SOURCE_CONFIG.update_time IS '更新时间';
