#!/bin/bash

### 将用户输入的端口写入 server_port.conf 文件.
CGI_PROXY_CONFIG_FILE="/var/apps/App.Native.flyNarwhalServer/target/ui/server_port.conf"
# 读取环境变量（${变量:-} 避免变量未定义时报错）
CGI_PROXY_PORT="${wizard_server_port:-}"

# 检测环境变量 wizard_server_port 值不为空，则将值写入 server_port.conf 文件
if [ -n "${CGI_PROXY_PORT}" ]; then
    echo "export CGI_PROXY_PORT=${CGI_PROXY_PORT}" > "${CGI_PROXY_CONFIG_FILE}"
    # 设置文件权限为 644
    chmod 644 "${CGI_PROXY_CONFIG_FILE}"
fi

exit 0