DROP TABLE IF EXISTS SERIES_EPISODES;
DROP TABLE IF EXISTS EPISODE_SEGMENTS;

CREATE TABLE IF NOT EXISTS SERIES_EPISODES (
    series_guid VARCHAR(255) NOT NULL PRIMARY KEY,
    season_folder_path VARCHAR(2048)
);

CREATE TABLE IF NOT EXISTS EPISODE_SEGMENTS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid VARCHAR(255),
    series_guid VARCHAR(255),
    file_path VARCHAR(2048),
    episode_index INT,
    duration DOUBLE,
    intro_start DOUBLE,
    intro_end DOUBLE,
    credits_start DOUBLE,
    credits_end DOUBLE,
    intro_fingerprint BLOB,
    credits_fingerprint BLOB
);
